#!/usr/bin/env bash
# Configuration a Nginx server to listen on port 80

# remove the default nginx congfiuration file
rm /etc/nginx/sites-enabled/default

# configure nginx to listen on port 80 for all active IPV4 IPS

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# resart nginx

service nginx restart
