#!/usr/bin/env bash
# This script display current process

printf "%-10s %-5s %-5s %-6s %-6s %-6s %-6s %-6s %-10s %s\n" \
	"USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "START" "TIME" "COMMAND"

ps aux --forest | awk '{printf "%-10s %-5s %-5s %-6s %-6s %-6s %-6s %-6s %-10s %s\n",
 $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11}'
