#!/usr/bin/env bash
# This print Best school 10 times while i less than 10
i=1

while [ $i -lt 11 ]
do
    echo "Best school"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done
	 
